feat(components): styles, postmessage
ticketcrm-com/tbx-widget pull request #17
Opened 2023-08-18 01:13 UTC by kocetora

2023-08-18 07:30 UTC, nosovk commented on packages/lib/src/TBXModal.wc.svelte
> +      class="container__content"
этот класс нигде не используется (да и в целом благодаря изоляции можно сразу iframe писать

2023-08-18 07:31 UTC, nosovk commented on packages/lib/src/TBXModal.wc.svelte
>    onMount(() => {
хм, вариант с await не подошел почему-то?

2023-08-18 07:35 UTC, nosovk commented on packages/lib/src/TBXModal.wc.svelte
> +    &__content {
не уподобляйся bem, пиши просто сразу нормальный селектор - iframe в нашем случае

2023-08-18 07:37 UTC, nosovk commented on packages/lib/src/TBXWidget.wc.svelte
> +  const getGa = () => {
тут тоже можно промис вернуть на самом деле ведь

2023-08-18 07:40 UTC, nosovk commented on packages/lib/src/Loader.wc.svelte
> +<div class="preloader">
там в ридми есть convention, что компоненты без wc в имени файла не компилируются в webcomponents, поэтому нужно переименовать в Loader.svelte

2023-08-18 07:41 UTC, nosovk commented on packages/lib/src/TBXModal.wc.svelte
> +    --modal-color: #800000;
эти переменные нужно вынести и описать на странице с демо. как часть инструкции по кастомизации

2023-08-18 07:43 UTC, nosovk commented on packages/lib/src/TBXModal.wc.svelte
> +  iframe,
в следующем же блоке iframe width\height переопределятся, зачем тогда они тут?

2023-08-18 07:43 UTC, nosovk requested changes
see comments

2023-08-29 06:36 UTC, nosovk commented on packages/demo/index.html
> +    <!-- <link
если не нужно - сносим

2023-08-29 06:36 UTC, nosovk commented on packages/demo/src/App.svelte
> +  let thanksUrl = "";
я бы через // записал комментарий с примерами значений, либо вверху jsdoc

2023-09-05 07:12 UTC, kocetora commented
feat(): working components and constructor

2023-09-05 07:15 UTC, merged